### PR TITLE
Change time for Datetime

### PR DESCRIPTION
**Pull request by Aldione**
Hi

Could we change the time for the exactly time? for example at 15:02 show a picture and at 15:08 show another picture and at 15:19 another one...

Something like this:
$ ./python-showcase.py -s -t 1502 /home/sergio/images/1.png
$ ./python-showcase.py -s -t 1508 /home/sergio/images/2.png

i can write in spanish but i wrote in english if someone can help us!

Thanks1

### CODE REVIEW

**Comment by Aldione** [comment]
Hi

Could we change the time for the exactly time? for example at 15:02 show a picture and at 15:08 show another picture and at 15:19 another one...

Something like this:
$ ./python-showcase.py -s -t 1502 /home/sergio/images/1.png
$ ./python-showcase.py -s -t 1508 /home/sergio/images/2.png

i can write in spanish but i wrote in english if someone can help us!

Thanks1

**Comment by cgoldberg** [comment]
what is this?

**Comment by Aldione** [comment]
I was trying to communicate with you by private but i cant, its possible to change the time with the real time? i mean with the clock.

**Comment by cgoldberg** [comment]
I don't understand the changes.  Why did you change the copyrights, project name, etc?  Definitely not merging this to my repo.

**Comment by Aldione** [comment]
Listen mate, i didnt change anything! i just saw this project on internet! and i just comment here to know if you can change it!

It's very simple... i need something like this, but not with second, just with the real time, for example this project is with 10 seconds (10000) can slip the imagen, so i want that at 03:02PM change to another imagen!

Did you understood? 

I didnt made this project, just comment on it

**Pull request closed without merging**
